# Import Libraries and Load Data

In [185]:
import pandas as pd
import sklearn

In [187]:
training_data = pd.read_csv("C:/Users/User/Desktop/DBSTT2/AI Dataset/ClientCreditRating (Training Data).csv")

In [188]:
testing_data = pd.read_csv("C:/Users/User/Desktop/DBSTT2/AI Dataset/ClientCreditRating (Testing Data).csv")

In [369]:
candidate = pd.read_csv("C:/Users/User/Desktop/DBSTT2/AI Dataset/ClientParticulars (Candidate_s Copy).csv")

# Random Forest Model

In [190]:
training_data

,CreditWorthy,Age,Education,MonthlyIncome,MarriageStatus,HasChildren,ExistingLoan,PurposeOfLoan
0,Yes,41,Master,6000,Single,Yes,Yes,Holiday
1,Yes,54,Diploma,10000,Married,Yes,No,Housing
2,Yes,73,Bachelor,9000,Married,Yes,No,Investment
3,Yes,66,Master,14000,Single,Yes,No,Housing
4,No,88,Diploma,2000,Single,No,No,Housing
...,...,...,...,...,...,...,...,...
105,Yes,73,Diploma,6000,Single,Yes,No,Investment
106,Yes,54,Diploma,5000,Single,Yes,No,Business Loan
107,No,86,Diploma,2000,Married,No,Yes,Business Loan
108,No,70,Master,3000,Married,Yes,No,Business Loan
109,Yes,47,Bachelor,6000,Single,Yes,No,Business Loan

In [191]:
testing_data

,CreditWorthy,Age,Education,MonthlyIncome,MarriageStatus,HasChildren,ExistingLoan,PurposeOfLoan
0,Yes,75,PhD,10000,Single,Yes,Yes,Housing
1,Yes,53,PhD,15000,Single,No,Yes,Housing
2,Yes,81,Diploma,7000,Married,No,No,Investment
3,Yes,45,Master,12000,Single,No,Yes,Holiday
4,Yes,21,Bachelor,10000,Single,Yes,Yes,Housing
5,No,93,PhD,10000,Single,No,Yes,Business Loan
6,No,64,Master,5000,Single,No,Yes,Investment
7,No,85,PhD,14000,Married,Yes,No,Business Loan
8,Yes,70,PhD,8000,Married,No,No,Housing
9,Yes,75,Master,13000,Married,Yes,Yes,Holiday
10,Yes,60,Diploma,7000,Single,No,No,Holiday
11,No,60,Master,6000,Married,No,No,Business Loan
12,Yes,50,PhD,7000,Married,Yes,No,Housing
13,Yes,79,Master,13000,Single,No,No,Holiday
14,Yes,60,Bachelor,14000,Single,Yes,Yes,Investment
15,No,94,Diploma,2000,Married,No,Yes,Housing
16,No,73,Bachelor,4000,Married,Yes,No,Investment
17,Yes,59,Master,12000,Single,Yes,No,Holiday
18,No,65,Diploma,7000,Single,No,Yes,Housing
19,No,90,Bachelor,12000,Single,Yes,Yes,Housing
20,No,61,PhD,4000,Married,No,No,Business Loan
21,Yes,21,Bachelor,5000,Married,No,No,Housing
22,Yes,24,Diploma,3000,Married,No,No,Investment
23,No,78,Bachelor,6000,Married,No,Yes,Business Loan
24,No,89,Bachelor,10000,Married,No,No,Housing
25,No,83,Diploma,8000,Single,Yes,Yes,Investment
26,Yes,38,Master,11000,Single,No,No,Business Loan
27,No,35,PhD,6000,Single,Yes,Yes,Business Loan
28,Yes,57,Master,8000,Married,Yes,No,Investment
29,Yes,59,Diploma,8000,Single,No,No,Holiday
30,Yes,74,PhD,10000,Married,No,Yes,Holiday
31,No,88,Master,7000,Single,No,Yes,Business Loan
32,Yes,33,Diploma,10000,Single,Yes,Yes,Holiday
33,No,86,Diploma,5000,Single,No,Yes,Business Loan
34,Yes,50,Master,15000,Married,No,Yes,Housing
35,Yes,25,PhD,4000,Single,Yes,Yes,Holiday
36,No,34,PhD,4000,Single,No,Yes,Investment
37,No,91,Master,5000,Married,No,Yes,Housing
38,No,90,Master,3000,Married,No,Yes,Holiday
39,No,68,Master,2000,Single,No,Yes,Holiday

In [192]:
training_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CreditWorthy    110 non-null    object
 1   Age             110 non-null    int64
 2   Education       110 non-null    object
 3   MonthlyIncome   110 non-null    int64
 4   MarriageStatus  110 non-null    object
 5   HasChildren     110 non-null    object
 6   ExistingLoan    110 non-null    object
 7   PurposeOfLoan   110 non-null    object
dtypes: int64(2), object(6)
memory usage: 7.0+ KB

In [193]:
training_data.columns

Index(['CreditWorthy', 'Age', 'Education', 'MonthlyIncome', 'MarriageStatus',
       'HasChildren', 'ExistingLoan', 'PurposeOfLoan'],
      dtype='object')

In [195]:
training_data.loc[training_data["HasChildren"] == "Yes", "HasChildren"] = 1
training_data.loc[training_data["HasChildren"] == "No", "HasChildren"] = 0

In [196]:
training_data.loc[training_data["ExistingLoan"] == "Yes", "ExistingLoan"] = 1
training_data.loc[training_data["ExistingLoan"] == "No", "ExistingLoan"] = 0

In [197]:
training_data.loc[training_data["MarriageStatus"] == "Married", "MarriageStatus"] = 1
training_data.loc[training_data["MarriageStatus"] == "Single", "MarriageStatus"] = 0

In [198]:
training_data.loc[training_data["CreditWorthy"] == "Yes", "CreditWorthy"] = 1
training_data.loc[training_data["CreditWorthy"] == "No", "CreditWorthy"] = 0

In [199]:
training_data.loc[training_data["Education"] == "Diploma", "Education"] = 1
training_data.loc[training_data["Education"] == "Bachelor", "Education"] = 2
training_data.loc[training_data["Education"] == "Master", "Education"] = 3
training_data.loc[training_data["Education"] == "PhD", "Education"] = 4

In [200]:
training_data.loc[training_data["PurposeOfLoan"] == "Holiday", "PurposeOfLoan"] = 1
training_data.loc[training_data["PurposeOfLoan"] == "Housing", "PurposeOfLoan"] = 2
training_data.loc[training_data["PurposeOfLoan"] == "Investment", "PurposeOfLoan"] = 3
training_data.loc[training_data["PurposeOfLoan"] == "Business Loan", "PurposeOfLoan"] = 4

In [201]:
training_data = training_data.astype(int)

In [202]:
training_data.corr()

,CreditWorthy,Age,Education,MonthlyIncome,MarriageStatus,HasChildren,ExistingLoan,PurposeOfLoan
CreditWorthy,1.000000,-0.302902,0.027932,0.404660,-0.106145,0.138691,-0.111207,-0.335384
Age,-0.302902,1.000000,0.158811,-0.004843,0.000902,-0.051606,-0.008677,0.043885
Education,0.027932,0.158811,1.000000,0.208101,0.042524,-0.081830,0.116113,-0.020288
MonthlyIncome,0.404660,-0.004843,0.208101,1.000000,0.128047,-0.066361,-0.033336,0.047828
MarriageStatus,-0.106145,0.000902,0.042524,0.128047,1.000000,0.050916,-0.052073,0.081700
HasChildren,0.138691,-0.051606,-0.081830,-0.066361,0.050916,1.000000,-0.047016,-0.218626
ExistingLoan,-0.111207,-0.008677,0.116113,-0.033336,-0.052073,-0.047016,1.000000,-0.080959
PurposeOfLoan,-0.335384,0.043885,-0.020288,0.047828,0.081700,-0.218626,-0.080959,1.000000

In [203]:
from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y = train_test_split(training_data.drop('CreditWorthy', axis=1), training_data['CreditWorthy'], test_size=0.2, random_state=25)

In [204]:
testing_data.loc[testing_data["HasChildren"] == "Yes", "HasChildren"] = 1
testing_data.loc[testing_data["HasChildren"] == "No", "HasChildren"] = 0

testing_data.loc[testing_data["ExistingLoan"] == "Yes", "ExistingLoan"] = 1
testing_data.loc[testing_data["ExistingLoan"] == "No", "ExistingLoan"] = 0

testing_data.loc[testing_data["MarriageStatus"] == "Married", "MarriageStatus"] = 1
testing_data.loc[testing_data["MarriageStatus"] == "Single", "MarriageStatus"] = 0

testing_data.loc[testing_data["CreditWorthy"] == "Yes", "CreditWorthy"] = 1
testing_data.loc[testing_data["CreditWorthy"] == "No", "CreditWorthy"] = 0

testing_data.loc[testing_data["Education"] == "Diploma", "Education"] = 1
testing_data.loc[testing_data["Education"] == "Bachelor", "Education"] = 2
testing_data.loc[testing_data["Education"] == "Master", "Education"] = 3
testing_data.loc[testing_data["Education"] == "PhD", "Education"] = 4

testing_data.loc[testing_data["PurposeOfLoan"] == "Holiday", "PurposeOfLoan"] = 1
testing_data.loc[testing_data["PurposeOfLoan"] == "Housing", "PurposeOfLoan"] = 2
testing_data.loc[testing_data["PurposeOfLoan"] == "Investment", "PurposeOfLoan"] = 3
testing_data.loc[testing_data["PurposeOfLoan"] == "Business Loan", "PurposeOfLoan"] = 4
testing_data = testing_data.astype(int)

In [205]:
from sklearn import model_selection
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
rfc.fit(training_data.drop('CreditWorthy', axis=1),training_data['CreditWorthy'])

rfc_predict = rfc.predict(testing_data.drop('CreditWorthy', axis=1))

In [206]:
rfc_predict

array([1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1])

In [207]:
rfc.score(test_x, test_y)

1.0

In [208]:
from sklearn import metrics

metrics.accuracy_score(testing_data['CreditWorthy'], rfc_predict)

0.775

In [209]:
for i in [100,150,200,400,600,900]:
    for j in [5,7,None]:
        for k in ['entropy','gini']:
            rfc = RandomForestClassifier(n_estimators = i, max_depth = j,random_state = 25 ,criterion = k)
            rfc.fit(training_data.drop(['CreditWorthy','Education'], axis=1),training_data['CreditWorthy'])
            rfc_predict = rfc.predict(testing_data.drop(['CreditWorthy','Education'], axis=1))
            roc_auc = metrics.roc_auc_score(testing_data['CreditWorthy'], rfc_predict)
            accuracy = metrics.accuracy_score(testing_data['CreditWorthy'], rfc_predict)
            print('i='+str(i) + 'j:' + str(j) + ' roc_auc:' + str(roc_auc) + ' accuracy:' + str(accuracy))

i=100j:5 roc_auc:0.7418546365914787 accuracy:0.75
i=100j:5 roc_auc:0.7418546365914787 accuracy:0.75
i=100j:7 roc_auc:0.8208020050125314 accuracy:0.825
i=100j:7 roc_auc:0.8208020050125314 accuracy:0.825
i=100j:None roc_auc:0.794486215538847 accuracy:0.8
i=100j:None roc_auc:0.8208020050125314 accuracy:0.825
i=150j:5 roc_auc:0.7681704260651628 accuracy:0.775
i=150j:5 roc_auc:0.7418546365914787 accuracy:0.75
i=150j:7 roc_auc:0.8208020050125314 accuracy:0.825
i=150j:7 roc_auc:0.8208020050125314 accuracy:0.825
i=150j:None roc_auc:0.8208020050125314 accuracy:0.825
i=150j:None roc_auc:0.8208020050125314 accuracy:0.825
i=200j:5 roc_auc:0.7155388471177946 accuracy:0.725
i=200j:5 roc_auc:0.7418546365914787 accuracy:0.75
i=200j:7 roc_auc:0.7681704260651628 accuracy:0.775
i=200j:7 roc_auc:0.794486215538847 accuracy:0.8
i=200j:None roc_auc:0.794486215538847 accuracy:0.8
i=200j:None roc_auc:0.794486215538847 accuracy:0.8
i=400j:5 roc_auc:0.7418546365914787 accuracy:0.75
i=400j:5 roc_auc:0.7418546365914787 accuracy:0.75
i=400j:7 roc_auc:0.794486215538847 accuracy:0.8
i=400j:7 roc_auc:0.794486215538847 accuracy:0.8
i=400j:None roc_auc:0.794486215538847 accuracy:0.8
i=400j:None roc_auc:0.794486215538847 accuracy:0.8
i=600j:5 roc_auc:0.7418546365914787 accuracy:0.75
i=600j:5 roc_auc:0.7418546365914787 accuracy:0.75
i=600j:7 roc_auc:0.8208020050125314 accuracy:0.825
i=600j:7 roc_auc:0.794486215538847 accuracy:0.8
i=600j:None roc_auc:0.794486215538847 accuracy:0.8
i=600j:None roc_auc:0.794486215538847 accuracy:0.8
i=900j:5 roc_auc:0.7418546365914787 accuracy:0.75
i=900j:5 roc_auc:0.7418546365914787 accuracy:0.75
i=900j:7 roc_auc:0.794486215538847 accuracy:0.8
i=900j:7 roc_auc:0.8208020050125314 accuracy:0.825
i=900j:None roc_auc:0.8471177944862155 accuracy:0.85
i=900j:None roc_auc:0.8208020050125314 accuracy:0.825

In [210]:
training_data[training_data['CreditWorthy']== 0].size

312

In [211]:
rfc_predict[rfc_predict==1]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [212]:
rfc_predict[rfc_predict==0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Data Cleaning

In [370]:
candidate

,FirstName,LastName,Gender,Age,MarriageStatus,PhoneNumber,NetYearlyIncome,HighValueIndividual
0,Maisy,O'Doherty,NaN,NaN,NaN,NaN,NaN,NaN
1,Maisy,O'Doherty,Female,26.0,Single,488 238-8338maisyodoherty@gmail.com,73000.0,No
2,Ellis,Ross,Female,66.0,Married,(830) 694-4738ellisross@gmail.com,176000.0,No
3,Dana,Oconnor,Female,52.0,Married,(296)855-2148danaoconnor@gmail.com,266000.0,No
4,Gareth,Ferrell,Male,46.0,Single,882400-9859garethferrell@gmail.com,729000.0,Yes
...,...,...,...,...,...,...,...,...
105,Kaya,Carrillo,Male,31.0,Single,(314)431-7751kayacarrillo@gmail.com,252000.0,No
106,Cormac,Moyer,Male,40.0,Married,(609) 350-3771cormacmoyer@gmail.com,78000.0,No
107,Cade,Watts,Male,NaN,Married,(827) 222-0618cadewatts@gmail.com,645000.0,NaN
108,Evelyn,Brandt,Female,58.0,Married,(930) 546-6988evelynbrandt@gmail.com,470000.0,Yes
109,Ammar,Dunlap,Male,66.0,Married,(271) 705-7576ammardunlap@gmail.com,474000.0,Yes

In [371]:
candidate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   FirstName            109 non-null    object
 1   LastName             109 non-null    object
 2   Gender               106 non-null    object
 3   Age                  95 non-null     float64
 4   MarriageStatus       95 non-null     object
 5   PhoneNumber          106 non-null    object
 6   NetYearlyIncome      106 non-null    float64
 7   HighValueIndividual  95 non-null     object
dtypes: float64(2), object(6)
memory usage: 7.0+ KB

In [372]:
candidate.dropna(subset= ['Gender','Age','FirstName','LastName','MarriageStatus','HighValueIndividual'],inplace = True)

In [373]:
candidate

,FirstName,LastName,Gender,Age,MarriageStatus,PhoneNumber,NetYearlyIncome,HighValueIndividual
1,Maisy,O'Doherty,Female,26.0,Single,488 238-8338maisyodoherty@gmail.com,73000.0,No
2,Ellis,Ross,Female,66.0,Married,(830) 694-4738ellisross@gmail.com,176000.0,No
3,Dana,Oconnor,Female,52.0,Married,(296)855-2148danaoconnor@gmail.com,266000.0,No
4,Gareth,Ferrell,Male,46.0,Single,882400-9859garethferrell@gmail.com,729000.0,Yes
6,Jemma,Sloan,Female,41.0,Married,(730)864-9016jemmasloan@gmail.com,480000.0,Yes
8,Lilly-Rose,Humphrey,Female,29.0,Single,(897) 854-9070lilly-rosehumphrey@gmail.com,368000.0,Yes
9,Ruairi,Schmidt,Male,30.0,Single,(766) 325-9938ruairischmidt@gmail.com,936000.0,Yes
10,Cody,Drake,Male,56.0,Married,(740) 812-6242codydrake@gmail.com,283000.0,No
11,Mark,Barton,Male,52.0,Married,(635) 350-3681markbarton@gmail.com,33000.0,No
12,Mackenzie,Stone,Female,74.0,Single,502860-7035mackenziestone@gmail.com,83000.0,No
14,Joao,Thomas,Male,77.0,Married,(868) 694-8380joaothomas@gmail.com,328000.0,Yes
15,Sumayyah,Andersen,Female,39.0,Married,(333) 528-2260sumayyahandersen@gmail.com,311000.0,Yes
16,Hermione,Chambers,Female,55.0,Married,(733) 520-5821hermionechambers@gmail.com,167000.0,No
17,Filip,Maldonado,Male,27.0,Single,(759) 460-8220filipmaldonado@gmail.com,787000.0,Yes
18,Keanu,Quinn,Male,43.0,Married,(750) 8496452keanuquinn@gmail.com,354000.0,Yes
20,Ray,Schultz,Male,33.0,Single,(450) 9767499rayschultz@gmail.com,64000.0,No
21,Catherine,Johnson,Female,58.0,Married,(475) 356-6995catherinejohnson@gmail.com,320000.0,Yes
22,Kasey,Hartley,Male,55.0,Married,(734) 941-7926kaseyhartley@gmail.com,572000.0,Yes
23,Sasha,Connorrr,Female,48.0,Single,(340) 653-2348sashaconnor@gmail.com,714000.0,Yes
24,Sasha,Connor,Female,48.0,Single,(340) 653-2348sashaconnor@gmail.com,714000.0,Yes
25,Jannat,Harris,Female,41.0,Married,(266) 318-6686jannatharris@gmail.com,783000.0,Yes
26,Alessandro,Pratt,Male,61.0,Married,390 590-0537alessandropratt@gmail.com,441000.0,Yes
28,Rebekah,Escobar,Male,32.0,Single,(819) 275-2204rebekahescobar@gmail.com,200000.0,No
29,Stephen,Dorsey,Male,21.0,Single,528 724-4113stephendorsey@gmail.com,232000.0,No
32,Fred,Blake,Male,57.0,Married,(433) 735-3551fredblake@gmail.com,883000.0,Yes
34,Victoria,Gallegos,Female,40.0,Single,(953) 954-5828victoriagallegos@gmail.com,840000.0,Yes
35,Ewan,Osborne,Male,59.0,Married,(875) 253-6641ewanosborne@gmail.com,917000.0,Yes
36,Shanice,Nolan,Female,20.0,Single,785423-0264shanicenolan@gmail.com,941000.0,Yes
37,Chantelle,Payne,Female,76.0,Married,(424) 304-5939chantellepayne@gmail.com,63000.0,No
38,Aleena,Evans,Female,61.0,Married,(381) 666-5997aleenaevans@gmail.com,468000.0,Yes
40,Lennon,Sharp,Female,61.0,Married,(672) 549-8462lennonsharp@gmail.com,584000.0,Yes
42,Arianna,Mosley,Female,26.0,Single,701 608-6760ariannamosley@gmail.com,585000.0,Yes
43,Juanita,Combs,Female,77.0,Married,(579) 481-0993juanitacombs@gmail.com,877000.0,Yes
45,Aneesa,Hodge,Female,23.0,Single,(695) 352-8648aneesahodge@gmail.com,206000.0,No
46,Yasmin,Solomon,Female,55.0,Married,8038249485yasminsolomon@gmail.com,38000.0,No
47,Daisie,Munoz,Female,29.0,Single,(966) 688-4835daisiemunoz@gmail.com,510000.0,Yes
48,Elizabeth,David,Female,25.0,Single,(641) 968-0402elizabethdavid@gmail.com,723000.0,Yes
49,Zayd,Schaefer,Male,37.0,Married,(348) 492-8623zaydschaefer@gmail.com,538000.0,Yes
52,Ada,Harding,Female,52.0,Married,(503) 619-4334adaharding@gmail.com,539000.0,Yes
53,Erica,Vaughn,Male,25.0,Single,840 538-5791ericavaughn@gmail.com,536000.0,Yes
54,Kacie,Nichols,Male,36.0,Married,(919) 2778103kacienichols@gmail.com,441000.0,Yes
55,Zahraa,Hooood,Female,49.0,Married,(228) 486-2441zahraahood@gmail.com,641000.0,Yes
56,Zahraa,Hood,Female,49.0,Married,(228) 486-2441zahraahood@gmail.com,641000.0,Yes
57,Zahraaaa,Hood,Female,49.0,Married,(228) 486-2441zahraahood@gmail.com,641000.0,Yes
59,Brayden,Barr,Male,41.0,Married,(404) 541-4224braydenbarr@gmail.com,806000.0,Yes
61,Willie,French,Female,70.0,Single,(371) 598-8892williefrench@gmail.com,873000.0,Yes
62,Louis,Cortez,Male,77.0,Married,(319) 511-4814louiscortez@gmail.com,186000.0,No
66,Lexi,Leonard,Female,38.0,Married,(591) 773-5129lexileonard@gmail.com,275000.0,No
67,Jim,Pham,Male,59.0,Married,(373) 365-5459jimpham@gmail.com,979000.0,Yes
68,Ahmad,Wood,Male,22.0,Single,(523) 689-6132ahmadwood@gmail.com,161000.0,No
69,Zak,Hickman,Male,48.0,Married,(217) 444-2442zakhickman@gmail.com,367000.0,Yes
71,Dale,Guerra,Male,78.0,Married,(706) 8440745daleguerra@gmail.com,48000.0,No
72,Clyde,Arroyo,Male,22.0,Single,(316) 869-0671clydearroyo@gmail.com,665000.0,Yes
74,Jazmine,Ali,Female,76.0,Married,(773) 394-5356jazmineali@gmail.com,225000.0,No
76,Isobella,Poole,Female,41.0,Married,(448) 390-3990isobellapoole@gmail.com,119000.0,No
78,Dalton,Mitchell,Male,44.0,Married,735962-2244daltonmitchell@gmail.com,157000.0,No
79,Sylvie,Hoover,Female,41.0,Married,(887) 806-9452sylviehoover@gmail.com,969000.0,Yes
80,Chester,Chandler,Male,31.0,Single,(393) 493-2882chesterchandler@gmail.com,991000.0,Yes
81,Ruth,Mullins,Female,41.0,Married,(819) 792-8587ruthmullins@gmail.com,206000.0,No
82,Ruther,Mullins,Female,41.0,Married,(819) 792-8587ruthmullins@gmail.com,206000.0,No
83,Ruther,Mullinss,Female,41.0,Married,(819) 792-8587ruthmullins@gmail.com,206000.0,No
84,Ruther,Mull,Female,41.0,Married,(819) 792-8587ruthmullins@gmail.com,206000.0,No
85,Annalise,Freeman,Female,43.0,Married,(416) 888-8194annalisefreeman@gmail.com,148000.0,No
86,Kelsey,Mcleod,Female,71.0,Married,(263) 407-0811kelseymcleod@gmail.com,361000.0,Yes
87,Isobelle,Foley,Female,23.0,Single,(419) 696-3155isobellefoley@gmail.com,791000.0,Yes
88,Findlay,Gordon,Male,35.0,Single,(410) 694-0839findlaygordon@gmail.com,979000.0,Yes
91,Sufyan,Wyatt,Male,75.0,Married,(437) 592-7260sufyanwyatt@gmail.com,233000.0,No
92,Ariana,Carr,Female,25.0,Single,(692) 397-3719arianacarr@gmail.com,830000.0,Yes
94,Gianluca,O'Quinn,Male,27.0,Single,(319) 442-7442gianlucaoquinn@gmail.com,266000.0,No
96,Rupert,Aguirre,Male,48.0,Married,(701) 259-8239rupertaguirre@gmail.com,334000.0,Yes
98,Bobby,Marshall,Female,76.0,Married,(795) 324-7525bobbymarshall@gmail.com,424000.0,Yes
99,Mathew,Mcmahon,Male,23.0,Single,(780) 841-4452mathewmcmahon@gmail.com,405000.0,Yes
100,Joanna,Shepherd,Female,58.0,Married,(277) 851-8223joannashepherd@gmail.com,972000.0,Yes
101,Elliot,Richard,Female,61.0,Married,(409) 625-8183elliotrichard@gmail.com,327000.0,Yes
102,Sufyaan,Whitney,Male,56.0,Married,(718) 313-1815sufyaanwhitney@gmail.com,825000.0,Yes
104,Celia,Matthams,Female,23.0,Single,(937) 625-4308celiamatthams@gmail.com,501000.0,Yes
105,Kaya,Carrillo,Male,31.0,Single,(314)431-7751kayacarrillo@gmail.com,252000.0,No
106,Cormac,Moyer,Male,40.0,Married,(609) 350-3771cormacmoyer@gmail.com,78000.0,No
108,Evelyn,Brandt,Female,58.0,Married,(930) 546-6988evelynbrandt@gmail.com,470000.0,Yes
109,Ammar,Dunlap,Male,66.0,Married,(271) 705-7576ammardunlap@gmail.com,474000.0,Yes

In [374]:
pd.set_option('display.max_rows',100)

In [375]:
candidate['Email'] = candidate['PhoneNumber'].str.extract(r'([a-zA-Z][a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]+)')
candidate['PhoneNumber'] = candidate['PhoneNumber'].str.extract(r'([\(]?[+]?[0-9]+[\s+]?[\(]?[\-]?[0-9]+[\)]?[\s+]?[0-9]+[\s+]?[\-]?[0-9]+)')

In [376]:
candidate

,FirstName,LastName,Gender,Age,MarriageStatus,PhoneNumber,NetYearlyIncome,HighValueIndividual,Email
1,Maisy,O'Doherty,Female,26.0,Single,488 238-8338,73000.0,No,maisyodoherty@gmail.com
2,Ellis,Ross,Female,66.0,Married,(830) 694-4738,176000.0,No,ellisross@gmail.com
3,Dana,Oconnor,Female,52.0,Married,(296)855-2148,266000.0,No,danaoconnor@gmail.com
4,Gareth,Ferrell,Male,46.0,Single,882400-9859,729000.0,Yes,garethferrell@gmail.com
6,Jemma,Sloan,Female,41.0,Married,(730)864-9016,480000.0,Yes,jemmasloan@gmail.com
8,Lilly-Rose,Humphrey,Female,29.0,Single,(897) 854-9070,368000.0,Yes,lilly-rosehumphrey@gmail.com
9,Ruairi,Schmidt,Male,30.0,Single,(766) 325-9938,936000.0,Yes,ruairischmidt@gmail.com
10,Cody,Drake,Male,56.0,Married,(740) 812-6242,283000.0,No,codydrake@gmail.com
11,Mark,Barton,Male,52.0,Married,(635) 350-3681,33000.0,No,markbarton@gmail.com
12,Mackenzie,Stone,Female,74.0,Single,502860-7035,83000.0,No,mackenziestone@gmail.com
14,Joao,Thomas,Male,77.0,Married,(868) 694-8380,328000.0,Yes,joaothomas@gmail.com
15,Sumayyah,Andersen,Female,39.0,Married,(333) 528-2260,311000.0,Yes,sumayyahandersen@gmail.com
16,Hermione,Chambers,Female,55.0,Married,(733) 520-5821,167000.0,No,hermionechambers@gmail.com
17,Filip,Maldonado,Male,27.0,Single,(759) 460-8220,787000.0,Yes,filipmaldonado@gmail.com
18,Keanu,Quinn,Male,43.0,Married,(750) 8496452,354000.0,Yes,keanuquinn@gmail.com
20,Ray,Schultz,Male,33.0,Single,(450) 9767499,64000.0,No,rayschultz@gmail.com
21,Catherine,Johnson,Female,58.0,Married,(475) 356-6995,320000.0,Yes,catherinejohnson@gmail.com
22,Kasey,Hartley,Male,55.0,Married,(734) 941-7926,572000.0,Yes,kaseyhartley@gmail.com
23,Sasha,Connorrr,Female,48.0,Single,(340) 653-2348,714000.0,Yes,sashaconnor@gmail.com
24,Sasha,Connor,Female,48.0,Single,(340) 653-2348,714000.0,Yes,sashaconnor@gmail.com
25,Jannat,Harris,Female,41.0,Married,(266) 318-6686,783000.0,Yes,jannatharris@gmail.com
26,Alessandro,Pratt,Male,61.0,Married,390 590-0537,441000.0,Yes,alessandropratt@gmail.com
28,Rebekah,Escobar,Male,32.0,Single,(819) 275-2204,200000.0,No,rebekahescobar@gmail.com
29,Stephen,Dorsey,Male,21.0,Single,528 724-4113,232000.0,No,stephendorsey@gmail.com
32,Fred,Blake,Male,57.0,Married,(433) 735-3551,883000.0,Yes,fredblake@gmail.com
34,Victoria,Gallegos,Female,40.0,Single,(953) 954-5828,840000.0,Yes,victoriagallegos@gmail.com
35,Ewan,Osborne,Male,59.0,Married,(875) 253-6641,917000.0,Yes,ewanosborne@gmail.com
36,Shanice,Nolan,Female,20.0,Single,785423-0264,941000.0,Yes,shanicenolan@gmail.com
37,Chantelle,Payne,Female,76.0,Married,(424) 304-5939,63000.0,No,chantellepayne@gmail.com
38,Aleena,Evans,Female,61.0,Married,(381) 666-5997,468000.0,Yes,aleenaevans@gmail.com
40,Lennon,Sharp,Female,61.0,Married,(672) 549-8462,584000.0,Yes,lennonsharp@gmail.com
42,Arianna,Mosley,Female,26.0,Single,701 608-6760,585000.0,Yes,ariannamosley@gmail.com
43,Juanita,Combs,Female,77.0,Married,(579) 481-0993,877000.0,Yes,juanitacombs@gmail.com
45,Aneesa,Hodge,Female,23.0,Single,(695) 352-8648,206000.0,No,aneesahodge@gmail.com
46,Yasmin,Solomon,Female,55.0,Married,8038249485,38000.0,No,yasminsolomon@gmail.com
47,Daisie,Munoz,Female,29.0,Single,(966) 688-4835,510000.0,Yes,daisiemunoz@gmail.com
48,Elizabeth,David,Female,25.0,Single,(641) 968-0402,723000.0,Yes,elizabethdavid@gmail.com
49,Zayd,Schaefer,Male,37.0,Married,(348) 492-8623,538000.0,Yes,zaydschaefer@gmail.com
52,Ada,Harding,Female,52.0,Married,(503) 619-4334,539000.0,Yes,adaharding@gmail.com
53,Erica,Vaughn,Male,25.0,Single,840 538-5791,536000.0,Yes,ericavaughn@gmail.com
54,Kacie,Nichols,Male,36.0,Married,(919) 2778103,441000.0,Yes,kacienichols@gmail.com
55,Zahraa,Hooood,Female,49.0,Married,(228) 486-2441,641000.0,Yes,zahraahood@gmail.com
56,Zahraa,Hood,Female,49.0,Married,(228) 486-2441,641000.0,Yes,zahraahood@gmail.com
57,Zahraaaa,Hood,Female,49.0,Married,(228) 486-2441,641000.0,Yes,zahraahood@gmail.com
59,Brayden,Barr,Male,41.0,Married,(404) 541-4224,806000.0,Yes,braydenbarr@gmail.com
61,Willie,French,Female,70.0,Single,(371) 598-8892,873000.0,Yes,williefrench@gmail.com
62,Louis,Cortez,Male,77.0,Married,(319) 511-4814,186000.0,No,louiscortez@gmail.com
66,Lexi,Leonard,Female,38.0,Married,(591) 773-5129,275000.0,No,lexileonard@gmail.com
67,Jim,Pham,Male,59.0,Married,(373) 365-5459,979000.0,Yes,jimpham@gmail.com
68,Ahmad,Wood,Male,22.0,Single,(523) 689-6132,161000.0,No,ahmadwood@gmail.com
69,Zak,Hickman,Male,48.0,Married,(217) 444-2442,367000.0,Yes,zakhickman@gmail.com
71,Dale,Guerra,Male,78.0,Married,(706) 8440745,48000.0,No,daleguerra@gmail.com
72,Clyde,Arroyo,Male,22.0,Single,(316) 869-0671,665000.0,Yes,clydearroyo@gmail.com
74,Jazmine,Ali,Female,76.0,Married,(773) 394-5356,225000.0,No,jazmineali@gmail.com
76,Isobella,Poole,Female,41.0,Married,(448) 390-3990,119000.0,No,isobellapoole@gmail.com
78,Dalton,Mitchell,Male,44.0,Married,735962-2244,157000.0,No,daltonmitchell@gmail.com
79,Sylvie,Hoover,Female,41.0,Married,(887) 806-9452,969000.0,Yes,sylviehoover@gmail.com
80,Chester,Chandler,Male,31.0,Single,(393) 493-2882,991000.0,Yes,chesterchandler@gmail.com
81,Ruth,Mullins,Female,41.0,Married,(819) 792-8587,206000.0,No,ruthmullins@gmail.com
82,Ruther,Mullins,Female,41.0,Married,(819) 792-8587,206000.0,No,ruthmullins@gmail.com
83,Ruther,Mullinss,Female,41.0,Married,(819) 792-8587,206000.0,No,ruthmullins@gmail.com
84,Ruther,Mull,Female,41.0,Married,(819) 792-8587,206000.0,No,ruthmullins@gmail.com
85,Annalise,Freeman,Female,43.0,Married,(416) 888-8194,148000.0,No,annalisefreeman@gmail.com
86,Kelsey,Mcleod,Female,71.0,Married,(263) 407-0811,361000.0,Yes,kelseymcleod@gmail.com
87,Isobelle,Foley,Female,23.0,Single,(419) 696-3155,791000.0,Yes,isobellefoley@gmail.com
88,Findlay,Gordon,Male,35.0,Single,(410) 694-0839,979000.0,Yes,findlaygordon@gmail.com
91,Sufyan,Wyatt,Male,75.0,Married,(437) 592-7260,233000.0,No,sufyanwyatt@gmail.com
92,Ariana,Carr,Female,25.0,Single,(692) 397-3719,830000.0,Yes,arianacarr@gmail.com
94,Gianluca,O'Quinn,Male,27.0,Single,(319) 442-7442,266000.0,No,gianlucaoquinn@gmail.com
96,Rupert,Aguirre,Male,48.0,Married,(701) 259-8239,334000.0,Yes,rupertaguirre@gmail.com
98,Bobby,Marshall,Female,76.0,Married,(795) 324-7525,424000.0,Yes,bobbymarshall@gmail.com
99,Mathew,Mcmahon,Male,23.0,Single,(780) 841-4452,405000.0,Yes,mathewmcmahon@gmail.com
100,Joanna,Shepherd,Female,58.0,Married,(277) 851-8223,972000.0,Yes,joannashepherd@gmail.com
101,Elliot,Richard,Female,61.0,Married,(409) 625-8183,327000.0,Yes,elliotrichard@gmail.com
102,Sufyaan,Whitney,Male,56.0,Married,(718) 313-1815,825000.0,Yes,sufyaanwhitney@gmail.com
104,Celia,Matthams,Female,23.0,Single,(937) 625-4308,501000.0,Yes,celiamatthams@gmail.com
105,Kaya,Carrillo,Male,31.0,Single,(314)431-7751,252000.0,No,kayacarrillo@gmail.com
106,Cormac,Moyer,Male,40.0,Married,(609) 350-3771,78000.0,No,cormacmoyer@gmail.com
108,Evelyn,Brandt,Female,58.0,Married,(930) 546-6988,470000.0,Yes,evelynbrandt@gmail.com
109,Ammar,Dunlap,Male,66.0,Married,(271) 705-7576,474000.0,Yes,ammardunlap@gmail.com

In [377]:
candidate['FullName'] = candidate['FirstName']+candidate['LastName']

In [378]:
candidate[candidate['Email'].str[0:-10].replace('\W', '',regex=True) != candidate['FullName'].str.lower().replace('\W','',regex=True)]

,FirstName,LastName,Gender,Age,MarriageStatus,PhoneNumber,NetYearlyIncome,HighValueIndividual,Email,FullName
23,Sasha,Connorrr,Female,48.0,Single,(340) 653-2348,714000.0,Yes,sashaconnor@gmail.com,SashaConnorrr
55,Zahraa,Hooood,Female,49.0,Married,(228) 486-2441,641000.0,Yes,zahraahood@gmail.com,ZahraaHooood
57,Zahraaaa,Hood,Female,49.0,Married,(228) 486-2441,641000.0,Yes,zahraahood@gmail.com,ZahraaaaHood
82,Ruther,Mullins,Female,41.0,Married,(819) 792-8587,206000.0,No,ruthmullins@gmail.com,RutherMullins
83,Ruther,Mullinss,Female,41.0,Married,(819) 792-8587,206000.0,No,ruthmullins@gmail.com,RutherMullinss
84,Ruther,Mull,Female,41.0,Married,(819) 792-8587,206000.0,No,ruthmullins@gmail.com,RutherMull

In [379]:
candidate[candidate['Email'].str[0:-10].replace('\W', '',regex=True) != candidate['FullName'].str.lower().replace('\W','',regex=True)].index

Int64Index([23, 55, 57, 82, 83, 84], dtype='int64')

In [380]:
candidate.drop([23, 55, 57, 82, 83, 84],inplace=True)

In [381]:
candidate.drop('FullName',axis=1,inplace=True)

In [382]:
candidate

,FirstName,LastName,Gender,Age,MarriageStatus,PhoneNumber,NetYearlyIncome,HighValueIndividual,Email
1,Maisy,O'Doherty,Female,26.0,Single,488 238-8338,73000.0,No,maisyodoherty@gmail.com
2,Ellis,Ross,Female,66.0,Married,(830) 694-4738,176000.0,No,ellisross@gmail.com
3,Dana,Oconnor,Female,52.0,Married,(296)855-2148,266000.0,No,danaoconnor@gmail.com
4,Gareth,Ferrell,Male,46.0,Single,882400-9859,729000.0,Yes,garethferrell@gmail.com
6,Jemma,Sloan,Female,41.0,Married,(730)864-9016,480000.0,Yes,jemmasloan@gmail.com
8,Lilly-Rose,Humphrey,Female,29.0,Single,(897) 854-9070,368000.0,Yes,lilly-rosehumphrey@gmail.com
9,Ruairi,Schmidt,Male,30.0,Single,(766) 325-9938,936000.0,Yes,ruairischmidt@gmail.com
10,Cody,Drake,Male,56.0,Married,(740) 812-6242,283000.0,No,codydrake@gmail.com
11,Mark,Barton,Male,52.0,Married,(635) 350-3681,33000.0,No,markbarton@gmail.com
12,Mackenzie,Stone,Female,74.0,Single,502860-7035,83000.0,No,mackenziestone@gmail.com
14,Joao,Thomas,Male,77.0,Married,(868) 694-8380,328000.0,Yes,joaothomas@gmail.com
15,Sumayyah,Andersen,Female,39.0,Married,(333) 528-2260,311000.0,Yes,sumayyahandersen@gmail.com
16,Hermione,Chambers,Female,55.0,Married,(733) 520-5821,167000.0,No,hermionechambers@gmail.com
17,Filip,Maldonado,Male,27.0,Single,(759) 460-8220,787000.0,Yes,filipmaldonado@gmail.com
18,Keanu,Quinn,Male,43.0,Married,(750) 8496452,354000.0,Yes,keanuquinn@gmail.com
20,Ray,Schultz,Male,33.0,Single,(450) 9767499,64000.0,No,rayschultz@gmail.com
21,Catherine,Johnson,Female,58.0,Married,(475) 356-6995,320000.0,Yes,catherinejohnson@gmail.com
22,Kasey,Hartley,Male,55.0,Married,(734) 941-7926,572000.0,Yes,kaseyhartley@gmail.com
24,Sasha,Connor,Female,48.0,Single,(340) 653-2348,714000.0,Yes,sashaconnor@gmail.com
25,Jannat,Harris,Female,41.0,Married,(266) 318-6686,783000.0,Yes,jannatharris@gmail.com
26,Alessandro,Pratt,Male,61.0,Married,390 590-0537,441000.0,Yes,alessandropratt@gmail.com
28,Rebekah,Escobar,Male,32.0,Single,(819) 275-2204,200000.0,No,rebekahescobar@gmail.com
29,Stephen,Dorsey,Male,21.0,Single,528 724-4113,232000.0,No,stephendorsey@gmail.com
32,Fred,Blake,Male,57.0,Married,(433) 735-3551,883000.0,Yes,fredblake@gmail.com
34,Victoria,Gallegos,Female,40.0,Single,(953) 954-5828,840000.0,Yes,victoriagallegos@gmail.com
35,Ewan,Osborne,Male,59.0,Married,(875) 253-6641,917000.0,Yes,ewanosborne@gmail.com
36,Shanice,Nolan,Female,20.0,Single,785423-0264,941000.0,Yes,shanicenolan@gmail.com
37,Chantelle,Payne,Female,76.0,Married,(424) 304-5939,63000.0,No,chantellepayne@gmail.com
38,Aleena,Evans,Female,61.0,Married,(381) 666-5997,468000.0,Yes,aleenaevans@gmail.com
40,Lennon,Sharp,Female,61.0,Married,(672) 549-8462,584000.0,Yes,lennonsharp@gmail.com
42,Arianna,Mosley,Female,26.0,Single,701 608-6760,585000.0,Yes,ariannamosley@gmail.com
43,Juanita,Combs,Female,77.0,Married,(579) 481-0993,877000.0,Yes,juanitacombs@gmail.com
45,Aneesa,Hodge,Female,23.0,Single,(695) 352-8648,206000.0,No,aneesahodge@gmail.com
46,Yasmin,Solomon,Female,55.0,Married,8038249485,38000.0,No,yasminsolomon@gmail.com
47,Daisie,Munoz,Female,29.0,Single,(966) 688-4835,510000.0,Yes,daisiemunoz@gmail.com
48,Elizabeth,David,Female,25.0,Single,(641) 968-0402,723000.0,Yes,elizabethdavid@gmail.com
49,Zayd,Schaefer,Male,37.0,Married,(348) 492-8623,538000.0,Yes,zaydschaefer@gmail.com
52,Ada,Harding,Female,52.0,Married,(503) 619-4334,539000.0,Yes,adaharding@gmail.com
53,Erica,Vaughn,Male,25.0,Single,840 538-5791,536000.0,Yes,ericavaughn@gmail.com
54,Kacie,Nichols,Male,36.0,Married,(919) 2778103,441000.0,Yes,kacienichols@gmail.com
56,Zahraa,Hood,Female,49.0,Married,(228) 486-2441,641000.0,Yes,zahraahood@gmail.com
59,Brayden,Barr,Male,41.0,Married,(404) 541-4224,806000.0,Yes,braydenbarr@gmail.com
61,Willie,French,Female,70.0,Single,(371) 598-8892,873000.0,Yes,williefrench@gmail.com
62,Louis,Cortez,Male,77.0,Married,(319) 511-4814,186000.0,No,louiscortez@gmail.com
66,Lexi,Leonard,Female,38.0,Married,(591) 773-5129,275000.0,No,lexileonard@gmail.com
67,Jim,Pham,Male,59.0,Married,(373) 365-5459,979000.0,Yes,jimpham@gmail.com
68,Ahmad,Wood,Male,22.0,Single,(523) 689-6132,161000.0,No,ahmadwood@gmail.com
69,Zak,Hickman,Male,48.0,Married,(217) 444-2442,367000.0,Yes,zakhickman@gmail.com
71,Dale,Guerra,Male,78.0,Married,(706) 8440745,48000.0,No,daleguerra@gmail.com
72,Clyde,Arroyo,Male,22.0,Single,(316) 869-0671,665000.0,Yes,clydearroyo@gmail.com
74,Jazmine,Ali,Female,76.0,Married,(773) 394-5356,225000.0,No,jazmineali@gmail.com
76,Isobella,Poole,Female,41.0,Married,(448) 390-3990,119000.0,No,isobellapoole@gmail.com
78,Dalton,Mitchell,Male,44.0,Married,735962-2244,157000.0,No,daltonmitchell@gmail.com
79,Sylvie,Hoover,Female,41.0,Married,(887) 806-9452,969000.0,Yes,sylviehoover@gmail.com
80,Chester,Chandler,Male,31.0,Single,(393) 493-2882,991000.0,Yes,chesterchandler@gmail.com
81,Ruth,Mullins,Female,41.0,Married,(819) 792-8587,206000.0,No,ruthmullins@gmail.com
85,Annalise,Freeman,Female,43.0,Married,(416) 888-8194,148000.0,No,annalisefreeman@gmail.com
86,Kelsey,Mcleod,Female,71.0,Married,(263) 407-0811,361000.0,Yes,kelseymcleod@gmail.com
87,Isobelle,Foley,Female,23.0,Single,(419) 696-3155,791000.0,Yes,isobellefoley@gmail.com
88,Findlay,Gordon,Male,35.0,Single,(410) 694-0839,979000.0,Yes,findlaygordon@gmail.com
91,Sufyan,Wyatt,Male,75.0,Married,(437) 592-7260,233000.0,No,sufyanwyatt@gmail.com
92,Ariana,Carr,Female,25.0,Single,(692) 397-3719,830000.0,Yes,arianacarr@gmail.com
94,Gianluca,O'Quinn,Male,27.0,Single,(319) 442-7442,266000.0,No,gianlucaoquinn@gmail.com
96,Rupert,Aguirre,Male,48.0,Married,(701) 259-8239,334000.0,Yes,rupertaguirre@gmail.com
98,Bobby,Marshall,Female,76.0,Married,(795) 324-7525,424000.0,Yes,bobbymarshall@gmail.com
99,Mathew,Mcmahon,Male,23.0,Single,(780) 841-4452,405000.0,Yes,mathewmcmahon@gmail.com
100,Joanna,Shepherd,Female,58.0,Married,(277) 851-8223,972000.0,Yes,joannashepherd@gmail.com
101,Elliot,Richard,Female,61.0,Married,(409) 625-8183,327000.0,Yes,elliotrichard@gmail.com
102,Sufyaan,Whitney,Male,56.0,Married,(718) 313-1815,825000.0,Yes,sufyaanwhitney@gmail.com
104,Celia,Matthams,Female,23.0,Single,(937) 625-4308,501000.0,Yes,celiamatthams@gmail.com
105,Kaya,Carrillo,Male,31.0,Single,(314)431-7751,252000.0,No,kayacarrillo@gmail.com
106,Cormac,Moyer,Male,40.0,Married,(609) 350-3771,78000.0,No,cormacmoyer@gmail.com
108,Evelyn,Brandt,Female,58.0,Married,(930) 546-6988,470000.0,Yes,evelynbrandt@gmail.com
109,Ammar,Dunlap,Male,66.0,Married,(271) 705-7576,474000.0,Yes,ammardunlap@gmail.com

In [383]:
candidate['PhoneNumber'] = candidate['PhoneNumber'].replace('\W', '',regex=True)

In [384]:
def format_phone_number(row):
    #number = row['PhoneNumber']
    temp = '(' + row[:3]+') '+row[3:6] +'-' + row[6:]
    return temp

In [385]:
candidate['PhoneNumber'] = candidate['PhoneNumber'].apply(lambda df: format_phone_number(df))

In [386]:
candidate

,FirstName,LastName,Gender,Age,MarriageStatus,PhoneNumber,NetYearlyIncome,HighValueIndividual,Email
1,Maisy,O'Doherty,Female,26.0,Single,(488) 238-8338,73000.0,No,maisyodoherty@gmail.com
2,Ellis,Ross,Female,66.0,Married,(830) 694-4738,176000.0,No,ellisross@gmail.com
3,Dana,Oconnor,Female,52.0,Married,(296) 855-2148,266000.0,No,danaoconnor@gmail.com
4,Gareth,Ferrell,Male,46.0,Single,(882) 400-9859,729000.0,Yes,garethferrell@gmail.com
6,Jemma,Sloan,Female,41.0,Married,(730) 864-9016,480000.0,Yes,jemmasloan@gmail.com
8,Lilly-Rose,Humphrey,Female,29.0,Single,(897) 854-9070,368000.0,Yes,lilly-rosehumphrey@gmail.com
9,Ruairi,Schmidt,Male,30.0,Single,(766) 325-9938,936000.0,Yes,ruairischmidt@gmail.com
10,Cody,Drake,Male,56.0,Married,(740) 812-6242,283000.0,No,codydrake@gmail.com
11,Mark,Barton,Male,52.0,Married,(635) 350-3681,33000.0,No,markbarton@gmail.com
12,Mackenzie,Stone,Female,74.0,Single,(502) 860-7035,83000.0,No,mackenziestone@gmail.com
14,Joao,Thomas,Male,77.0,Married,(868) 694-8380,328000.0,Yes,joaothomas@gmail.com
15,Sumayyah,Andersen,Female,39.0,Married,(333) 528-2260,311000.0,Yes,sumayyahandersen@gmail.com
16,Hermione,Chambers,Female,55.0,Married,(733) 520-5821,167000.0,No,hermionechambers@gmail.com
17,Filip,Maldonado,Male,27.0,Single,(759) 460-8220,787000.0,Yes,filipmaldonado@gmail.com
18,Keanu,Quinn,Male,43.0,Married,(750) 849-6452,354000.0,Yes,keanuquinn@gmail.com
20,Ray,Schultz,Male,33.0,Single,(450) 976-7499,64000.0,No,rayschultz@gmail.com
21,Catherine,Johnson,Female,58.0,Married,(475) 356-6995,320000.0,Yes,catherinejohnson@gmail.com
22,Kasey,Hartley,Male,55.0,Married,(734) 941-7926,572000.0,Yes,kaseyhartley@gmail.com
24,Sasha,Connor,Female,48.0,Single,(340) 653-2348,714000.0,Yes,sashaconnor@gmail.com
25,Jannat,Harris,Female,41.0,Married,(266) 318-6686,783000.0,Yes,jannatharris@gmail.com
26,Alessandro,Pratt,Male,61.0,Married,(390) 590-0537,441000.0,Yes,alessandropratt@gmail.com
28,Rebekah,Escobar,Male,32.0,Single,(819) 275-2204,200000.0,No,rebekahescobar@gmail.com
29,Stephen,Dorsey,Male,21.0,Single,(528) 724-4113,232000.0,No,stephendorsey@gmail.com
32,Fred,Blake,Male,57.0,Married,(433) 735-3551,883000.0,Yes,fredblake@gmail.com
34,Victoria,Gallegos,Female,40.0,Single,(953) 954-5828,840000.0,Yes,victoriagallegos@gmail.com
35,Ewan,Osborne,Male,59.0,Married,(875) 253-6641,917000.0,Yes,ewanosborne@gmail.com
36,Shanice,Nolan,Female,20.0,Single,(785) 423-0264,941000.0,Yes,shanicenolan@gmail.com
37,Chantelle,Payne,Female,76.0,Married,(424) 304-5939,63000.0,No,chantellepayne@gmail.com
38,Aleena,Evans,Female,61.0,Married,(381) 666-5997,468000.0,Yes,aleenaevans@gmail.com
40,Lennon,Sharp,Female,61.0,Married,(672) 549-8462,584000.0,Yes,lennonsharp@gmail.com
42,Arianna,Mosley,Female,26.0,Single,(701) 608-6760,585000.0,Yes,ariannamosley@gmail.com
43,Juanita,Combs,Female,77.0,Married,(579) 481-0993,877000.0,Yes,juanitacombs@gmail.com
45,Aneesa,Hodge,Female,23.0,Single,(695) 352-8648,206000.0,No,aneesahodge@gmail.com
46,Yasmin,Solomon,Female,55.0,Married,(803) 824-9485,38000.0,No,yasminsolomon@gmail.com
47,Daisie,Munoz,Female,29.0,Single,(966) 688-4835,510000.0,Yes,daisiemunoz@gmail.com
48,Elizabeth,David,Female,25.0,Single,(641) 968-0402,723000.0,Yes,elizabethdavid@gmail.com
49,Zayd,Schaefer,Male,37.0,Married,(348) 492-8623,538000.0,Yes,zaydschaefer@gmail.com
52,Ada,Harding,Female,52.0,Married,(503) 619-4334,539000.0,Yes,adaharding@gmail.com
53,Erica,Vaughn,Male,25.0,Single,(840) 538-5791,536000.0,Yes,ericavaughn@gmail.com
54,Kacie,Nichols,Male,36.0,Married,(919) 277-8103,441000.0,Yes,kacienichols@gmail.com
56,Zahraa,Hood,Female,49.0,Married,(228) 486-2441,641000.0,Yes,zahraahood@gmail.com
59,Brayden,Barr,Male,41.0,Married,(404) 541-4224,806000.0,Yes,braydenbarr@gmail.com
61,Willie,French,Female,70.0,Single,(371) 598-8892,873000.0,Yes,williefrench@gmail.com
62,Louis,Cortez,Male,77.0,Married,(319) 511-4814,186000.0,No,louiscortez@gmail.com
66,Lexi,Leonard,Female,38.0,Married,(591) 773-5129,275000.0,No,lexileonard@gmail.com
67,Jim,Pham,Male,59.0,Married,(373) 365-5459,979000.0,Yes,jimpham@gmail.com
68,Ahmad,Wood,Male,22.0,Single,(523) 689-6132,161000.0,No,ahmadwood@gmail.com
69,Zak,Hickman,Male,48.0,Married,(217) 444-2442,367000.0,Yes,zakhickman@gmail.com
71,Dale,Guerra,Male,78.0,Married,(706) 844-0745,48000.0,No,daleguerra@gmail.com
72,Clyde,Arroyo,Male,22.0,Single,(316) 869-0671,665000.0,Yes,clydearroyo@gmail.com
74,Jazmine,Ali,Female,76.0,Married,(773) 394-5356,225000.0,No,jazmineali@gmail.com
76,Isobella,Poole,Female,41.0,Married,(448) 390-3990,119000.0,No,isobellapoole@gmail.com
78,Dalton,Mitchell,Male,44.0,Married,(735) 962-2244,157000.0,No,daltonmitchell@gmail.com
79,Sylvie,Hoover,Female,41.0,Married,(887) 806-9452,969000.0,Yes,sylviehoover@gmail.com
80,Chester,Chandler,Male,31.0,Single,(393) 493-2882,991000.0,Yes,chesterchandler@gmail.com
81,Ruth,Mullins,Female,41.0,Married,(819) 792-8587,206000.0,No,ruthmullins@gmail.com
85,Annalise,Freeman,Female,43.0,Married,(416) 888-8194,148000.0,No,annalisefreeman@gmail.com
86,Kelsey,Mcleod,Female,71.0,Married,(263) 407-0811,361000.0,Yes,kelseymcleod@gmail.com
87,Isobelle,Foley,Female,23.0,Single,(419) 696-3155,791000.0,Yes,isobellefoley@gmail.com
88,Findlay,Gordon,Male,35.0,Single,(410) 694-0839,979000.0,Yes,findlaygordon@gmail.com
91,Sufyan,Wyatt,Male,75.0,Married,(437) 592-7260,233000.0,No,sufyanwyatt@gmail.com
92,Ariana,Carr,Female,25.0,Single,(692) 397-3719,830000.0,Yes,arianacarr@gmail.com
94,Gianluca,O'Quinn,Male,27.0,Single,(319) 442-7442,266000.0,No,gianlucaoquinn@gmail.com
96,Rupert,Aguirre,Male,48.0,Married,(701) 259-8239,334000.0,Yes,rupertaguirre@gmail.com
98,Bobby,Marshall,Female,76.0,Married,(795) 324-7525,424000.0,Yes,bobbymarshall@gmail.com
99,Mathew,Mcmahon,Male,23.0,Single,(780) 841-4452,405000.0,Yes,mathewmcmahon@gmail.com
100,Joanna,Shepherd,Female,58.0,Married,(277) 851-8223,972000.0,Yes,joannashepherd@gmail.com
101,Elliot,Richard,Female,61.0,Married,(409) 625-8183,327000.0,Yes,elliotrichard@gmail.com
102,Sufyaan,Whitney,Male,56.0,Married,(718) 313-1815,825000.0,Yes,sufyaanwhitney@gmail.com
104,Celia,Matthams,Female,23.0,Single,(937) 625-4308,501000.0,Yes,celiamatthams@gmail.com
105,Kaya,Carrillo,Male,31.0,Single,(314) 431-7751,252000.0,No,kayacarrillo@gmail.com
106,Cormac,Moyer,Male,40.0,Married,(609) 350-3771,78000.0,No,cormacmoyer@gmail.com
108,Evelyn,Brandt,Female,58.0,Married,(930) 546-6988,470000.0,Yes,evelynbrandt@gmail.com
109,Ammar,Dunlap,Male,66.0,Married,(271) 705-7576,474000.0,Yes,ammardunlap@gmail.com

In [387]:
candidate.to_csv('ClientParticulars (Candidate_s Copy)_cleaned.csv')